package paivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 15:10:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HavaintoTest {


  // Generated by ComTest BEGIN
  /** testRekisterointi48 */
  @Test
  public void testRekisterointi48() {    // Havainto: 48
    Havainto panda = new Havainto(); 
    assertEquals("From: Havainto line: 50", 0, panda.getID()); 
    panda.rekisterointi(); 
    Havainto tiikeri = new Havainto(); 
    tiikeri.rekisterointi(); 
    int n1 = panda.getID(); 
    int n2 = tiikeri.getID(); 
    assertEquals("From: Havainto line: 56", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse183 */
  @Test
  public void testParse183() {    // Havainto: 183
    Havainto h = new Havainto(); 
    h.parse("1   |  Hauki    | Järvi"); 
    assertEquals("From: Havainto line: 186", 1, h.getID()); 
    assertEquals("From: Havainto line: 187", true, h.toString().startsWith("1|Hauki|Järvi|")); 
    h.rekisterointi(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta215 */
  @Test
  public void testAseta215() {    // Havainto: 215
    Havainto h = new Havainto(); 
    assertEquals("From: Havainto line: 217", null, h.aseta(1, "hirvi")); 
    assertEquals("From: Havainto line: 218", null, h.aseta(4, "kesä 2017")); 
    assertEquals("From: Havainto line: 219", null, h.aseta(4, "24.2.2022")); 
  } // Generated by ComTest END
}