package paivakirja.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 15:14:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HavainnotTest {



  // Generated by ComTest BEGIN
  /** testLisaa57 */
  @Test
  public void testLisaa57() {    // Havainnot: 57
    Havainnot havainnot = new Havainnot(); 
    Havainto panda = new Havainto(); 
    Havainto tiikeri = new Havainto(); 
    assertEquals("From: Havainnot line: 61", 0, havainnot.getLkm()); 
    havainnot.lisaa(panda); 
    havainnot.lisaa(tiikeri); 
    havainnot.lisaa(tiikeri); 
    assertEquals("From: Havainnot line: 65", panda, havainnot.anna(0)); 
    assertEquals("From: Havainnot line: 66", tiikeri, havainnot.anna(1)); 
    assertEquals("From: Havainnot line: 67", tiikeri, havainnot.anna(2)); 
    assertEquals("From: Havainnot line: 68", false, havainnot.anna(1) == panda); 
    assertEquals("From: Havainnot line: 69", true, havainnot.anna(1) == tiikeri); 
    havainnot.lisaa(panda); 
    havainnot.lisaa(tiikeri); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto97 
   * @throws TilaException when error
   */
  @Test
  public void testLueTiedosto97() throws TilaException {    // Havainnot: 97
    Havainnot h = new Havainnot(); 
    Havainto kauris = new Havainto(); kauris.vastaa(); 
    Havainto kauris2 = new Havainto(); kauris2.vastaa(); 
    Havainto kauris3 = new Havainto(); kauris3.vastaa(); 
    String nimi = "testi"; 
    File file = new File(nimi + "/havainnot.dat"); 
    file.delete(); 
    try {
    h.lueTiedosto(nimi); 
    fail("Havainnot: 107 Did not throw TilaException");
    } catch(TilaException _e_){ _e_.getMessage(); }
    h.lisaa(kauris); 
    h.lisaa(kauris2); 
    h.lisaa(kauris3); 
    h.tallenna(nimi); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiID166 */
  @Test
  public void testEtsiID166() {    // Havainnot: 166
    Havainnot ht = new Havainnot(); 
    Havainto h = new Havainto(); h.rekisterointi(); ht.lisaa(h); 
    Havainto h2 = new Havainto(); h2.rekisterointi(); ht.lisaa(h2); 
    Havainto h3 = new Havainto(); h3.rekisterointi(); ht.lisaa(h3); 
    assertEquals("From: Havainnot line: 171", -1, ht.etsiID(24)); 
    assertEquals("From: Havainnot line: 172", -1, ht.etsiID(111)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista188 */
  @Test
  public void testPoista188() {    // Havainnot: 188
    Havainnot ht = new Havainnot(); 
    Havainto h = new Havainto(); h.rekisterointi(); ht.lisaa(h); 
    Havainto h2 = new Havainto(); h2.rekisterointi(); ht.lisaa(h2); 
    Havainto h3 = new Havainto(); h3.rekisterointi(); ht.lisaa(h3); 
    int id = 2; 
    assertEquals("From: Havainnot line: 194", 1, ht.poista(id)); 
    assertEquals("From: Havainnot line: 195", 0, ht.poista(id+3)); 
    assertEquals("From: Havainnot line: 196", 2, ht.getLkm()); 
  } // Generated by ComTest END
}