package paivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 15:12:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LajiTest {


  // Generated by ComTest BEGIN
  /** testRekisterointi65 */
  @Test
  public void testRekisterointi65() {    // Laji: 65
    Laji panda = new Laji(); 
    assertEquals("From: Laji line: 67", 0, panda.getID()); 
    panda.rekisterointi(); 
    Laji tiikeri = new Laji(); 
    tiikeri.rekisterointi(); 
    int n1 = panda.getID(); 
    int n2 = tiikeri.getID(); 
    assertEquals("From: Laji line: 73", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta262 */
  @Test
  public void testAseta262() {    // Laji: 262
    Laji s = new Laji(); 
    assertEquals("From: Laji line: 264", null, s.aseta(1, "panda")); 
    assertEquals("From: Laji line: 265", null, s.aseta(2, " ")); 
    assertEquals("From: Laji line: 266", null, s.aseta(2, "nisäkkäät")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse320 */
  @Test
  public void testParse320() {    // Laji: 320
    Laji l = new Laji(); 
    l.parse("1   |  Hauki    | Kala"); 
    assertEquals("From: Laji line: 323", 1, l.getID()); 
    assertEquals("From: Laji line: 324", true, l.toString().startsWith("1|Hauki|Kala|")); 
    l.rekisterointi(); 
  } // Generated by ComTest END
}