package paivakirja.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 13:27:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LajitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto54 
   * @throws TilaException when error
   */
  @Test
  public void testLueTiedosto54() throws TilaException {    // Lajit: 54
    Lajit h = new Lajit(); 
    Laji kauris = new Laji(); kauris.vastaa(1); 
    Laji kauris2 = new Laji(); kauris2.vastaa(2); 
    Laji kauris3 = new Laji(); kauris3.vastaa(3); 
    String nimi = "testi"; 
    File file = new File(nimi + "/lajit.dat"); 
    file.delete(); 
    try {
    h.lueTiedosto(nimi); 
    fail("Lajit: 64 Did not throw TilaException");
    } catch(TilaException _e_){ _e_.getMessage(); }
    h.lisaa(kauris); 
    h.lisaa(kauris2); 
    h.lisaa(kauris3); 
    try {
    h.tallenna(nimi); 
    fail("Lajit: 68 Did not throw TilaException");
    } catch(TilaException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}