package paivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 15:13:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivakirjaTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa47 
   * @throws TilaException when error
   */
  @Test
  public void testLisaa47() throws TilaException {    // Paivakirja: 47
    Paivakirja paivakirja = new Paivakirja(); 
    Havainto panda = new Havainto(); 
    Havainto tiikeri = new Havainto(); 
    assertEquals("From: Paivakirja line: 52", 0, paivakirja.getLukumaara()); 
    paivakirja.lisaa(panda); assertEquals("From: Paivakirja line: 53", 1, paivakirja.getLukumaara()); 
    paivakirja.lisaa(tiikeri); assertEquals("From: Paivakirja line: 54", 2, paivakirja.getLukumaara()); 
    paivakirja.lisaa(tiikeri); assertEquals("From: Paivakirja line: 55", 3, paivakirja.getLukumaara()); 
    assertEquals("From: Paivakirja line: 56", panda, paivakirja.annaHavainto(0)); 
    assertEquals("From: Paivakirja line: 57", tiikeri, paivakirja.annaHavainto(1)); 
    assertEquals("From: Paivakirja line: 58", tiikeri, paivakirja.annaHavainto(2)); 
    assertEquals("From: Paivakirja line: 59", false, paivakirja.annaHavainto(1) == panda); 
    assertEquals("From: Paivakirja line: 60", true, paivakirja.annaHavainto(1) == tiikeri); 
    try {
    assertEquals("From: Paivakirja line: 61", panda, paivakirja.annaHavainto(3)); 
    fail("Paivakirja: 61 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    paivakirja.lisaa(panda); assertEquals("From: Paivakirja line: 62", 4, paivakirja.getLukumaara()); 
    paivakirja.lisaa(tiikeri); assertEquals("From: Paivakirja line: 63", 5, paivakirja.getLukumaara()); 
  } // Generated by ComTest END
}